[package]
name = "self-executable-dynlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]


[dependencies]
nix = "0.26.2"
